
package com.luxsoft.cfdix.ediwin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.6
 * 2017-06-20T11:23:12.416-05:00
 * Generated source version: 2.6.6
 */

@WebFault(name = "fault", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
public class CFDiException_Exception extends Exception {
    
    private com.luxsoft.cfdix.ediwin.CFDiException fault;

    public CFDiException_Exception() {
        super();
    }
    
    public CFDiException_Exception(String message) {
        super(message);
    }
    
    public CFDiException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CFDiException_Exception(String message, com.luxsoft.cfdix.ediwin.CFDiException fault) {
        super(message);
        this.fault = fault;
    }

    public CFDiException_Exception(String message, com.luxsoft.cfdix.ediwin.CFDiException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.luxsoft.cfdix.ediwin.CFDiException getFaultInfo() {
        return this.fault;
    }
}
