package com.luxsoft.cfdix.ediwin;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2017-06-20T11:23:12.442-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "CFDiService", 
                  wsdlLocation = "src/wsdl/ediwin.wsdl",
                  targetNamespace = "http://cfdi.service.ediwinws.edicom.com") 
public class CFDiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cfdi.service.ediwinws.edicom.com", "CFDiService");
    public final static QName CFDi = new QName("http://cfdi.service.ediwinws.edicom.com", "CFDi");
    static {
        URL url = CFDiService.class.getResource("src/wsdl/ediwin.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CFDiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/wsdl/ediwin.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public CFDiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CFDiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CFDiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CFDiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CFDiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CFDiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CFDi
     */
    @WebEndpoint(name = "CFDi")
    public CFDi getCFDi() {
        return super.getPort(CFDi, CFDi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CFDi
     */
    @WebEndpoint(name = "CFDi")
    public CFDi getCFDi(WebServiceFeature... features) {
        return super.getPort(CFDi, CFDi.class, features);
    }

}
