package com.luxsoft.cfdix.ediwin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2017-06-20T11:23:12.424-05:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://cfdi.service.ediwinws.edicom.com", name = "CFDi")
@XmlSeeAlso({ObjectFactory.class})
public interface CFDi {

    @WebResult(name = "cancelaCFDiRetencionesSignedReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDiRetencionesSigned", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiRetencionesSigned")
    @WebMethod
    @ResponseWrapper(localName = "cancelaCFDiRetencionesSignedResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiRetencionesSignedResponse")
    public com.luxsoft.cfdix.ediwin.CancelaResponse cancelaCFDiRetencionesSigned(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign
    ) throws CFDiException_Exception;

    @WebResult(name = "getTimbreCfdiRetencionesTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdiRetencionesTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiRetencionesTest")
    @WebMethod
    @ResponseWrapper(localName = "getTimbreCfdiRetencionesTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiRetencionesTestResponse")
    public byte[] getTimbreCfdiRetencionesTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getUUIDTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getUUIDTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetUUIDTest")
    @WebMethod
    @ResponseWrapper(localName = "getUUIDTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetUUIDTestResponse")
    public java.lang.String getUUIDTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdi")
    @WebMethod
    @ResponseWrapper(localName = "getCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiResponse")
    public byte[] getCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getUUIDReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getUUID", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetUUID")
    @WebMethod
    @ResponseWrapper(localName = "getUUIDResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetUUIDResponse")
    public java.lang.String getUUID(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getCfdiTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiTest")
    @WebMethod
    @ResponseWrapper(localName = "getCfdiTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiTestResponse")
    public byte[] getCfdiTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getTimbreCfdiTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdiTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiTest")
    @WebMethod
    @ResponseWrapper(localName = "getTimbreCfdiTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiTestResponse")
    public byte[] getTimbreCfdiTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "exportCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "exportCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.ExportCfdi")
    @WebMethod
    @ResponseWrapper(localName = "exportCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.ExportCfdiResponse")
    public byte[] exportCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "iniDate", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        javax.xml.datatype.XMLGregorianCalendar iniDate,
        @WebParam(name = "endDate", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        javax.xml.datatype.XMLGregorianCalendar endDate
    ) throws CFDiException_Exception;

    @WebResult(name = "getCfdiFromUUIDReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiFromUUID", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiFromUUID")
    @WebMethod
    @ResponseWrapper(localName = "getCfdiFromUUIDResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiFromUUIDResponse")
    public byte[] getCfdiFromUUID(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid
    ) throws CFDiException_Exception;

    @WebResult(name = "cancelaCFDiSignedReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDiSigned", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiSigned")
    @WebMethod
    @ResponseWrapper(localName = "cancelaCFDiSignedResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiSignedResponse")
    public com.luxsoft.cfdix.ediwin.CancelaResponse cancelaCFDiSigned(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign
    ) throws CFDiException_Exception;

    @WebResult(name = "getCfdiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiRetenciones")
    @WebMethod
    @ResponseWrapper(localName = "getCfdiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiRetencionesResponse")
    public byte[] getCfdiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getTimbreCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdi")
    @WebMethod
    @ResponseWrapper(localName = "getTimbreCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiResponse")
    public byte[] getTimbreCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getCfdiAckReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiAck", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiAck")
    @WebMethod
    @ResponseWrapper(localName = "getCfdiAckResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiAckResponse")
    public byte[] getCfdiAck(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid
    ) throws CFDiException_Exception;

    @WebResult(name = "changePasswordReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.ChangePassword")
    @WebMethod
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.ChangePasswordResponse")
    public boolean changePassword(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "newPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String newPassword
    ) throws CFDiException_Exception;

    @WebResult(name = "cancelaCFDiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDi")
    @WebMethod
    @ResponseWrapper(localName = "cancelaCFDiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiResponse")
    public com.luxsoft.cfdix.ediwin.CancelaResponse cancelaCFDi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid,
        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,
        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String pfxPassword
    ) throws CFDiException_Exception;

    @WebResult(name = "getTimbreCfdiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiRetenciones")
    @WebMethod
    @ResponseWrapper(localName = "getTimbreCfdiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetTimbreCfdiRetencionesResponse")
    public byte[] getTimbreCfdiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "getCfdiRetencionesTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiRetencionesTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiRetencionesTest")
    @WebMethod
    @ResponseWrapper(localName = "getCfdiRetencionesTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.GetCfdiRetencionesTestResponse")
    public byte[] getCfdiRetencionesTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file
    ) throws CFDiException_Exception;

    @WebResult(name = "cancelaCFDiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiRetenciones")
    @WebMethod
    @ResponseWrapper(localName = "cancelaCFDiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.luxsoft.cfdix.ediwin.CancelaCFDiRetencionesResponse")
    public com.luxsoft.cfdix.ediwin.CancelaResponse cancelaCFDiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.util.List<java.lang.String> uuid,
        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,
        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        java.lang.String pfxPassword
    ) throws CFDiException_Exception;
}
